# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'filter_window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(255, 398)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.toolButton = QtWidgets.QToolButton(Dialog)
        self.toolButton.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout_3.addWidget(self.toolButton)
        self.resourceBox = QtWidgets.QComboBox(Dialog)
        self.resourceBox.setObjectName("resourceBox")
        self.horizontalLayout_3.addWidget(self.resourceBox)
        self.syncButton = QtWidgets.QToolButton(Dialog)
        self.syncButton.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.syncButton.setObjectName("syncButton")
        self.horizontalLayout_3.addWidget(self.syncButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.locationLabel = QtWidgets.QLabel(Dialog)
        self.locationLabel.setObjectName("locationLabel")
        self.verticalLayout.addWidget(self.locationLabel)
        self.locationBox = QtWidgets.QComboBox(Dialog)
        self.locationBox.setMinimumSize(QtCore.QSize(170, 0))
        self.locationBox.setObjectName("locationBox")
        self.verticalLayout.addWidget(self.locationBox)
        spacerItem2 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.sortLabel = QtWidgets.QLabel(Dialog)
        self.sortLabel.setObjectName("sortLabel")
        self.verticalLayout.addWidget(self.sortLabel)
        self.sortBox = QtWidgets.QComboBox(Dialog)
        self.sortBox.setMinimumSize(QtCore.QSize(170, 0))
        self.sortBox.setObjectName("sortBox")
        self.verticalLayout.addWidget(self.sortBox)
        self.sortBox2 = QtWidgets.QComboBox(Dialog)
        self.sortBox2.setEnabled(False)
        self.sortBox2.setMinimumSize(QtCore.QSize(170, 0))
        self.sortBox2.setObjectName("sortBox2")
        self.verticalLayout.addWidget(self.sortBox2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem3)
        self.algoLabel = QtWidgets.QLabel(Dialog)
        self.algoLabel.setObjectName("algoLabel")
        self.verticalLayout.addWidget(self.algoLabel)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.algoBox = QtWidgets.QComboBox(Dialog)
        self.algoBox.setObjectName("algoBox")
        self.horizontalLayout_2.addWidget(self.algoBox)
        self.algoPercent = QtWidgets.QSpinBox(Dialog)
        self.algoPercent.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.algoPercent.sizePolicy().hasHeightForWidth())
        self.algoPercent.setSizePolicy(sizePolicy)
        self.algoPercent.setMinimumSize(QtCore.QSize(0, 0))
        self.algoPercent.setMinimum(1)
        self.algoPercent.setMaximum(50)
        self.algoPercent.setProperty("value", 10)
        self.algoPercent.setObjectName("algoPercent")
        self.horizontalLayout_2.addWidget(self.algoPercent)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem4)
        self.startButton = QtWidgets.QPushButton(Dialog)
        self.startButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startButton.sizePolicy().hasHeightForWidth())
        self.startButton.setSizePolicy(sizePolicy)
        self.startButton.setMinimumSize(QtCore.QSize(170, 60))
        self.startButton.setObjectName("startButton")
        self.verticalLayout.addWidget(self.startButton)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Not a Key - Filters"))
        self.toolButton.setText(_translate("Dialog", "±"))
        self.syncButton.setText(_translate("Dialog", "🔄"))
        self.locationLabel.setText(_translate("Dialog", "Choose location:"))
        self.sortLabel.setText(_translate("Dialog", "Sort by:"))
        self.algoLabel.setText(_translate("Dialog", "Algorithm:"))
        self.startButton.setText(_translate("Dialog", "Start"))

